// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9glpkI62-PlkG1TXQYjw7pNnUHi8OO0E',
    appId: '1:251073816478:web:dbafe3c7ed60a6af7c588f',
    messagingSenderId: '251073816478',
    projectId: 'image-htp',
    authDomain: 'image-htp.firebaseapp.com',
    storageBucket: 'image-htp.firebasestorage.app',
    databaseURL: 'https://image-htp-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0apIp2Jz2px1vDru14Wa_xQML3CypPqg',
    appId: '1:251073816478:android:f551e3d60906f7bb7c588f',
    messagingSenderId: '251073816478',
    projectId: 'image-htp',
    storageBucket: 'image-htp.firebasestorage.app',
     databaseURL: 'https://image-htp-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmVRM5eG2WOeuyn06TmzY4sA2sr0XV70',
    appId: '1:251073816478:ios:fc5fcd2084da45a17c588f',
    messagingSenderId: '251073816478',
    projectId: 'image-htp',
    storageBucket: 'image-htp.firebasestorage.app',
    iosBundleId: 'com.example.htp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnmVRM5eG2WOeuyn06TmzY4sA2sr0XV70',
    appId: '1:251073816478:ios:fc5fcd2084da45a17c588f',
    messagingSenderId: '251073816478',
    projectId: 'image-htp',
    storageBucket: 'image-htp.firebasestorage.app',
    iosBundleId: 'com.example.htp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9glpkI62-PlkG1TXQYjw7pNnUHi8OO0E',
    appId: '1:251073816478:web:340deef924a7ceed7c588f',
    messagingSenderId: '251073816478',
    projectId: 'image-htp',
    authDomain: 'image-htp.firebaseapp.com',
    storageBucket: 'image-htp.firebasestorage.app',
  );

}